# This file provides instructions for packaging.

`Data-Dumper-GUI`
	perl_version_from m`Data::Dumper::GUI`;
	version_from      m`Data::Dumper::GUI`;
	readme_from       m`Data::Dumper::GUI` ;
	requires          p`Devel::Size 0.79`;
	requires          p`Exporter::Tiny 0.012`;
	requires          p`Moo 1.002000`;
	requires          p`Prima 1.36`;
	requires          p`Types::Standard 0.012`;
	.

